# Generated by Django 2.1.5 on 2019-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveIntegerField()),
                ('price_negotiable', models.CharField(max_length=50)),
                ('product_usage_age', models.CharField(max_length=200)),
                ('product_warranty', models.CharField(max_length=100)),
                ('product_image', models.FileField(default='product_image/no_image.png', upload_to='product_image/')),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_location', models.CharField(max_length=200)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(max_length=30)),
                ('seller_city', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('product_display_last_date', models.DateField()),
            ],
        ),
    ]
