# Generated by Django 2.1.5 on 2019-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='product_category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
